name: push-docker-image
on:
  push:
    tags:
      - "v*"
concurrency:
  group: ci-push-docker-image-${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: cicd
  EKS_CLUSTER: eks-stack

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Extract last tag
        id: meta
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Build & Upload image to ECR
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          registry: ${{ secrets.REGISTRY }} # ECR URI WITHOUT /REPONAME
          repo: ${{env.ECR_REPOSITORY}}
          region: ${{env.AWS_REGION}}
          tags: ${{ steps.meta.outputs.tag }}
          daemon_off: false
          dockerfile: ./Dockerfile
          context: ./
